apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 10.2.1
      helm:
        releaseName: argocd
        valueFiles:
          - $values/platform/argocd/values.yaml
    - repoURL: https://github.com/open-homelab-io/open-homelab.git
      targetRevision: swap-flannel-for-cilium
      ref: values
    - repoURL: https://github.com/open-homelab-io/open-homelab.git
      targetRevision: swap-flannel-for-cilium
      path: platform/argocd/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
