apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "65"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.15
      helm:
        releaseName: grafana
        valueFiles:
          - $values/platform/grafana/values.yaml
    - repoURL: https://github.com/open-homelab-io/open-homelab.git
      targetRevision: swap-flannel-for-cilium
      ref: values
    - repoURL: https://github.com/open-homelab-io/open-homelab.git
      targetRevision: swap-flannel-for-cilium
      path: platform/grafana/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
