apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: https://github.com/open-homelab-io/open-homelab.git
    targetRevision: swap-flannel-for-cilium
    path: platform/secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true

