apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secrets.yaml
  - postgres.yaml
  - keycloak.yaml
  - metrics-service.yaml
  - spi-metrics-service.yaml
  - bootstrap-admin-user-job.yaml
