apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-minio
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: mimir-minio
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        rootUser: grafana-mimir
        rootPassword: "{{ .root_password }}"
        MINIO_ROOT_PASSWORD: "{{ .root_password }}"
  data:
    - secretKey: root_password
      remoteRef:
        key: platform/observability/mimir/minio
        property: root_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
