apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-postgres
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  bootstrap:
    initdb:
      database: registry
      owner: harbor
      secret:
        name: harbor-secrets
  storage:
    storageClass: longhorn
    size: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi
  monitoring:
    enablePodMonitor: false
